default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: flight_mngt_dev

test:
  <<: *default
  database: flight_mngt_test

production:
  <<: *default
  database: flight_mngt_dev
